2019-08-09 12:17:09,412 ERROR: Exception on /index [GET] [in c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\routes.py", line 26, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-08-09 12:19:39,208 ERROR: Exception on /index [GET] [in c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\routes.py", line 26, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-08-09 12:19:44,530 ERROR: Exception on /index [GET] [in c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\routes.py", line 26, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\agustin\appdata\local\programs\python\python35\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-08-09 12:20:36,321 INFO: Microblog startup [in C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\__init__.py:47]
2019-08-09 12:29:51,368 INFO: Microblog startup [in C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\__init__.py:47]
2019-08-09 12:35:57,916 INFO: Microblog startup [in C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\__init__.py:47]
2019-08-09 12:39:55,813 INFO: Microblog startup [in C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\__init__.py:47]
2019-08-09 12:42:33,777 INFO: Microblog startup [in C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\__init__.py:47]
2019-08-09 13:09:21,089 INFO: Microblog startup [in C:\Users\agustin\Desktop\AI\FlaskApps - tutorial\HelloWorldApp\app\__init__.py:48]
